name: test Auto Update apache
on: 
  schedule:
    - cron: '0 23 * * *'  # Täglich um 23 Uhr UTC
  workflow_dispatch:  

jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2 # Checkt das Zielrepository aus
        with:
          repository: FaserF/hassio-addons # Hier den Benutzernamen und den Namen des Quellrepositories eintragen
          ref: main # Hier den Namen der Branch oder des Tags eintragen, von dem du kopieren möchtest
          path: source-repo # Hier den Pfad angeben, in den das Repository geklont werden soll


      - name: Copy folder to target repository
        run: |
          cp -r source-repo/apache2-minimal apache2-minimal # Hier den Pfad zum zu kopierenden Ordner und den Zielordner angeben
          ls

      - name: Setup Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'

      - name: Initialize target repository
        run: |
          git init
          git remote add origin https://github.com/mgallardo61/hassio_addons.git
          git fetch
          git checkout main

      - name: Add and commit changes
        run: |
          git add apache2-minimal
          git commit -m "Copy folder from another repository"
          git push
