name: Auto Update apache
on: 
  schedule:
    - cron: '0 23 * * *'  # Täglich um 23 Uhr UTC
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Checkout source repository
        uses: actions/checkout@v3 # Checkt das Zielrepository aus
        with:
          repository: FaserF/hassio-addons # Hier den Benutzernamen und den Namen des Quellrepositories eintragen
          ref: main # Hier den Namen der Branch oder des Tags eintragen, von dem du kopieren möchtest
          path: source-repo # Hier den Pfad angeben, in den das Repository geklont werden soll
      
      - name: Copy folder to target repository
        run: |
          cp -r source-repo/apache2-minimal . # Hier den Pfad zum zu kopierenden Ordner und den Zielordner angeben

      - name: replace mapping
        run: |
          sed -i 's/media:rw/config:rw/g' apache2-minimal/config.yaml
          sed -i 's/\/share\/htdocs/\/config\/apache/g' apache2-minimal/config.yaml

      - name: check if mapping was replaced
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat apache2-minimal/config.yaml
          contains: "config:rw"

      - name: remove cached source-repo
        run: |
          #git rm --cached source-repo
          
      - name: upload
        run: |
          git add apache2-minimal
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
