name: Auto Update metube
on: workflow_dispatch
jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      
      - name: get metube version
        id: get_metube_version
        run: |
          VERSION=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/alexta69/metube/releases/latest)
  
          echo "Container Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: replace metube version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.get_metube_version.outputs.version }}"/g' metube/config.json
          sed -i 's/"upstream": "[^"]*"/"upstream": "${{ steps.get_metube_version.outputs.version }}"/g' metube/config.json

      - name: check if metube version was replaced
        uses: GuillaumeFalourd/assert-command-line-output@v2
        with:
          command_line: cat metube/config.json
          contains: "${{ steps.get_metube_version.outputs.version }}"

      - name: upload
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
