name: Auto Update metube
on:
  schedule:
    - cron: '0 23 * * *'  # Täglich um 23 Uhr UTC
  workflow_dispatch:
        
jobs:
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get metube version
        id: get_metube_version
        run: |
          VERSION=$(curl -s "https://hub.docker.com/v2/repositories/alexta69/metube/tags" | jq -r '.results[1].name')
          echo "Container Version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        
      - name: replace metube version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.get_metube_version.outputs.version }}"/g' metube/config.json
          sed -i 's/"upstream": "[^"]*"/"upstream": "${{ steps.get_metube_version.outputs.version }}"/g' metube/config.json

      - name: check if metube version was replaced
        uses: GuillaumeFalourd/assert-command-line-output@v2.2
        with:
          command_line: cat metube/config.json
          contains: "${{ steps.get_metube_version.outputs.version }}"

      - name: remove output.txt
        run: |
          rm output.txt
          
      - name: upload
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name 'Your Name'
            git config --global user.email 'your-username@users.noreply.github.com'
            git commit -am "Automated report"
            git push
          else
           echo "No changes to commit."
          fi



        
          #git config --global user.name 'Your Name'
          #git config --global user.email 'your-username@users.noreply.github.com'
          #git commit -am "Automated report"
          #git push
